### ISSUE TITLE
Remove "user_images" folder from repo

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Lif-Auth-Server#10]
Remove the `user_images` folder from the repository and add it to the .gitignore. 

**Tasks**

- [ ] Move the `default.png` into an assets folder
- [ ] Remove the `user_images` folder from the repo
- [ ] Make Lif-Auth-Server automatically create this folder
- [ ] Add this folder to .gitignore
