### ISSUE TITLE
Create auto config system

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Lif-Auth-Server#17]
Create a system to automatically add configurations to the config.yml if they are missing. Also make the system create a new config.yml if missing.

### Tasks
- [x] Make server auto create the config file
- [x] Make server auto update config file 
- [x] Add config file to git ignore
